/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kaakaa_hoe' at '14/07/05 17:27' with Gradle 2.0
 *
 * @author kaakaa_hoe, @date 14/07/05 17:27
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
