package org.sample;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kaakaa_hoe' at '14/07/05 16:09' with Gradle 2.0
 *
 * @author kaakaa_hoe, @date 14/07/05 16:09
 */
public class Greet {
    public static void main(String[] args) {
        System.out.println("Hello application plugin");
    }
}
